!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  Kd_x: 2.5
  Kd_y: 2.5
  Kd_z: 4.0
  Kp_pitch: 15.0
  Kp_roll: 15.0
  Kp_x: 6.0
  Kp_y: 6.0
  Kp_yaw: 15.0
  Kp_z: 30.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      Kd_x: 2.5
      Kd_y: 2.5
      Kd_z: 4.0
      Kp_pitch: 15.0
      Kp_roll: 15.0
      Kp_x: 6.0
      Kp_y: 6.0
      Kp_yaw: 15.0
      Kp_z: 30.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      state: true
      type: ''
    state: []
state: []
